version: '3.8'

services:
  web:
    build: .
    container_name: sistema_processos_web
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: always
